### ISSUE TITLE
SQL Error on install.

### ISSUE THREAD

**Issue by dudeisbrendan03** [WatcherWhale/Software-License-Manager#1]
[02/10/2018 19:32:50] Setup (Account Creator) : (Error) ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'admin'', 'x' at line 1

MySQL 5.7 (remote host)
Node v8.2.0

**Comment by dudeisbrendan03** [comment]
I think you've made a typo - trying to create a row with invalid syntax (theres two apostrophes at the end of admin). I'm looking for the problem now

**Comment by dudeisbrendan03** [comment]
Value login is getting an added apostrophe when it goes into UserAuthenticator but I can't figure out why.

**Comment by dudeisbrendan03** [comment]
Just removed an apostrophe next to where you put login from UserAuthenticator when it inserts the new row, don't know where it's coming from.

**Comment by dudeisbrendan03** [comment]
oh and there was a missing semicolon at the end of the query for adding the user

**Comment by dudeisbrendan03** [comment]
Thought I resolved the issue - just added a load of issues further on.

**Comment by MostHated** [comment]
I just manually imported the sql files and was able to start it up. I get a login screen currently, but nothing happens if you submit. I have not had a chance to look any farther into it yet.

**Comment by dudeisbrendan03** [comment]
I've tried poking around and manually creating records but the login screen doesn't work. Is this project actually functional @WatcherWhale

**Comment by WatcherWhale** [comment]
The project is still in development! So not everything is functional yet. But I will look further into it first time I'm back behind a computer.

**Comment by dudeisbrendan03** [comment]
Good to hear

**Comment by WatcherWhale** [comment]
Normally it is fixed now. I added too many of these ' in the SQL in the Register function.
**By the way the project is long from finished**, but I'm working hard on it when I have time.

**Comment by dudeisbrendan03** [comment]
Are basic functions working like creating and checking keys

**Comment by WatcherWhale** [comment]
No not yet 😐 I tought of a secure system but I need to do a lot of research before i could get started.
Sorry 😶
